@startuml AttendanceSubSystem

left to right direction

skinparam Monochrome true
skinparam Shadowing false
skinparam packageStyle rectangle

actor Admin
actor Member

rectangle "Attendance System" {
    Admin --> (Generate QR Code)
    Member --> (Scan QR Code)

    (Scan QR Code) ..> (Update Attendance) : include
}

@enduml