@startuml ConfirmAttendance

skinparam Monochrome true
skinparam Shadowing false
hide footbox

actor Member
participant "Page: Ticket Detail" as TicketDetailPage
participant "Container: Ticket Detail" as TicketDetailContainer
participant "Service: Attendance Service" as FEAttendanceService
participant "Router" as Router
participant "Attendance: HTTP Transport" as AttendanceHTTPTransport
participant "Attendance: Endpoint" as AttendanceEndpoint
participant "Attendance: Service" as AttendanceService
participant "Requester: Service" as RequesterService
participant "Attendance: Command" as AttendanceCommand
participant "Attendance: Query" as AttendanceQuery

Member->TicketDetailPage: Click "Yes" Button
TicketDetailPage->TicketDetailContainer: handleConfirmation(input)
TicketDetailContainer->FEAttendanceService: confirmAttendance(classId, payload)
FEAttendanceService->Router: route("PATCH", "v2/class/{class_id}/attendance/confirmation")
Router->AttendanceHTTPTransport: Confirmation(AttendanceService, []ServerOption)
AttendanceHTTPTransport->AttendanceEndpoint: Confirmation(AttendanceService)
AttendanceEndpoint->AttendanceService: Confirmation(context, payload)
AttendanceService->AttendanceService: Validate()

alt "Data Not Valid"
    AttendanceService-->AttendanceEndpoint: UnprocessableEntity
    AttendanceEndpoint-->AttendanceHTTPTransport: UnprocessableEntity
    AttendanceHTTPTransport-->Router: UnprocessableEntity
    Router-->FEAttendanceService: UnprocessableEntity
    FEAttendanceService-->TicketDetailContainer: UnprocessableEntity
    TicketDetailContainer-->TicketDetailPage: UnprocessableEntity
    TicketDetailPage-->Member: UnprocessableEntity
else
    AttendanceService->AttendanceQuery: GetPureModel(context, []SliceCondition)
    AttendanceQuery-->AttendanceService: ticket

    alt "Ticket Status is Accepted"
        AttendanceService->AttendanceService: Register(context, []payload)
    else 
        AttendanceService->RequesterService: UpdateRequestStatus(context, ticket)
        RequesterService-->AttendanceService: is updated
    end 

    AttendanceService-->AttendanceEndpoint: is updated
    AttendanceEndpoint-->AttendanceEndpoint: response := Response(is updated, nil)
    AttendanceEndpoint-->AttendanceHTTPTransport: response
    AttendanceHTTPTransport-->Router: response
    Router-->FEAttendanceService: response
    FEAttendanceService-->TicketDetailContainer: response
    TicketDetailContainer-->TicketDetailPage: response
    TicketDetailPage-->Member: response
end

@enduml