@startuml GetCalendar

skinparam Monochrome true
skinparam Shadowing false
hide footbox

actor Admin
participant "Page: Dashboard" as Dashboard
participant "Service: Statistic Service" as FEStatisticService
participant "Router" as Router
participant "Statistic: HTTP Transport" as StatisticHTTPTransport
participant "Statistic: Endpoint" as StatisticEndpoint
participant "Statistic: Service" as StatisticService
participant "Statistic: Query" as StatisticQuery

Admin->Dashboard: Open "Dashboard" Page
Dashboard->Dashboard: fetchCalendar()
Dashboard->FEStatisticService: fetchCalendar(date)
FEStatisticService->Router: route("GET", "v2/statistic/calendar")
Router->StatisticHTTPTransport: FetchCalendar(StatisticService, []ServerOption)
StatisticHTTPTransport->StatisticEndpoint: GetCalendar(StatisticService)
StatisticEndpoint->StatisticService: Calendar(context, date)
StatisticService->StatisticQuery: FindCalendar(context, date)
StatisticQuery-->StatisticService: calendar
StatisticService-->StatisticEndpoint: calendar
StatisticEndpoint->StatisticEndpoint: response := Response(calendar, nil)
StatisticEndpoint-->StatisticHTTPTransport: response
StatisticHTTPTransport-->Router: response
Router-->FEStatisticService: response
FEStatisticService-->Dashboard: response
Dashboard->Dashboard: Render "Calendar"
Dashboard-->Admin: rendered

@enduml