@startuml DeleteRoomTransactionETL

skinparam ConditionEndStyle hline
skinparam conditionStyle diamond
skinparam Monochrome true
skinparam Shadowing false

|Caller|
start
:Delete Replica;

|System|
:Delete "Room Transaction" ETL data from Database;
split
    -> DELETED;
    :Add Success Information;
split again
    -> NOT DELETED;
    :Add Error Information;
end split
stop

@enduml