@startuml CommitFile

skinparam Monochrome true
skinparam Shadowing false
hide footbox

actor Caller
participant ":StorageService" as StorageService
participant ":LibraryStorage" as StorageLib
participant ":AWSS3" as S3

Caller->StorageService: CommitFile(context)
StorageService->StorageLib: RenameAllDirectoryFiles(outPath, path)
StorageLib-->StorageService: is exists
StorageService->StorageLib: Zip(path)
StorageLib-->StorageService: path
StorageService->StorageLib: FindFileNameFromExt(path, ext)
StorageLib-->StorageService: path
StorageService->S3: UplaodFileFromLocal(file, fileInfo)
S3-->StorageService: link
StorageService->StorageLib: Remove(path)
StorageLib-->StorageService: is removed
StorageService-->Caller: link

@enduml