@startuml CommitBooked

skinparam Monochrome true
skinparam Shadowing false
hide footbox

actor Caller
participant "Class: Service" as ClassService
participant "Class: Command" as ClassCommand

Caller->ClassService: CommitBooked(context, eventId)
ClassService->ClassCommand: CommitBooked(context, eventId, true)
ClassCommand-->ClassService: is commited
ClassService-->Caller: is commited

@enduml