@startuml CreateClass

skinparam Monochrome true
skinparam Shadowing false
hide footbox

actor Admin
participant "Page: Add Class" as AddClassPage
participant "Container: Add Class Form" as AddClassFormContainer
participant "Component: Class Form" as ClassForm
participant "Service: Class Service" as FEClassService
participant "Router" as Router
participant "Class: HTTP Transport" as ClassHTTPTransport
participant "Class: Endpoint" as ClassEndpoint
participant "Class: Service" as ClassService
participant "Class: Command" as ClassCommand
participant "Class: Query" as ClassQuery
participant "Storage: GRPC Transport" as StorageGRPCTransport
participant "Material: Service" as MaterialService

Admin->AddClassPage: Open "Add Class" Page
AddClassPage->AddClassFormContainer: Render "Add Class Form" Container
AddClassFormContainer->ClassForm: Render "Class Form"
ClassForm-->AddClassFormContainer: rendered
AddClassFormContainer-->AddClassPage: rendered
AddClassPage-->Admin: rendered

Admin->AddClassPage: Fill Form
AddClassPage->AddClassFormContainer: Fill Form
AddClassFormContainer->ClassForm: Fill Form
ClassForm-->AddClassFormContainer: form data
AddClassFormContainer-->AddClassPage: form data
AddClassPage-->Admin: form data

Admin->AddClassPage: Click "Create Class" Button
AddClassPage->AddClassFormContainer: handleClassFormSubmitted()
AddClassFormContainer->FEClassService: createClass(payload)
FEClassService->Router: route("POST", "v2/{event_id}/class", formData)
Router->ClassHTTPTransport: CreateClass(ClassService, []ServerOption)
ClassHTTPTransport->ClassEndpoint: Create(ClassService)
ClassEndpoint->ClassService: CreateMany(context, payload)

loop "for each payload"
    ClassService->ClassService: Validate()

    alt "Data not valid"
        break
            ClassService-->ClassEndpoint: UnprocessableEntity
            ClassEndpoint-->ClassHTTPTransport: UnprocessableEntity
            ClassHTTPTransport-->Router: UnprocessableEntity
            Router-->FEClassService: UnprocessableEntity
            FEClassService-->AddClassFormContainer: UnprocessableEntity
            AddClassFormContainer-->AddClassPage: UnprocessableEntity
            AddClassPage-->Admin: UnprocessableEntity
        end
    else
        ClassService->ClassService: class := ClassModel()
        ClassService->ClassCommand: Create(context, class)
        ClassCommand-->ClassService: uuid

        opt "has materials"
            ClassService->StorageGRPCTransport: CommitFile(context, ProtoBuffer)
            StorageGRPCTransport-->ClassService: link

            ClassService->MaterialService: Create(context, payload)
            MaterialService-->ClassService: isCreated
        end

        ClassService->ClassQuery: Find(context, []SliceConditions)
        ClassQuery-->ClassService: classes
    end

    ClassService-->ClassEndpoint: class
    ClassEndpoint->ClassEndpoint: response := Response(class, nil)
    ClassEndpoint-->ClassHTTPTransport: response
    ClassHTTPTransport-->Router: response
    Router-->FEClassService: response
    FEClassService-->AddClassFormContainer: response
    AddClassFormContainer-->AddClassPage: response
    AddClassPage-->Admin: response
end

@enduml