@startuml CreateRole

skinparam Monochrome true
skinparam Shadowing false
hide footbox

actor Admin
participant "Page: Add Role" as AddRolePage
participant "Container: Add Role Form" as AddRoleFormContainer
participant "Component: Role Form" as RoleForm
participant "Router" as Router
participant "Role: HTTP Transport" as RoleHTTPTransport
participant "Role: Endpoint" as RoleEndpoint
participant "Role: Service" as RoleService
participant "Role: Command" as RoleCommand
participant "Role: Query" as RoleQuery

activate Admin

Admin->AddRolePage: Open "Add Role" Page
activate AddRolePage
AddRolePage->AddRoleFormContainer: Render "Add Role Form" Container
activate AddRoleFormContainer
AddRoleFormContainer->RoleForm: Render "Role Form"
activate RoleForm
RoleForm-->AddRoleFormContainer
AddRoleFormContainer-->AddRolePage
AddRolePage-->Admin

Admin->AddRolePage: Fill Form
AddRolePage->AddRoleFormContainer: Fill Form
AddRoleFormContainer->RoleForm: Fill Form
RoleForm-->AddRoleFormContainer: form data
deactivate RoleForm
AddRoleFormContainer-->AddRolePage: form data
AddRolePage-->Admin: form data

Admin->AddRolePage: Click "Create Role" Button
AddRolePage->AddRoleFormContainer: Click "Create Role" Button
AddRoleFormContainer->Router: route("POST", "v2/role", formData)
activate Router
Router->RoleHTTPTransport: CreateRole(RoleService, []ServerOption)
activate RoleHTTPTransport
RoleHTTPTransport->RoleEndpoint: Create(RoleService)
activate RoleEndpoint
RoleEndpoint->RoleService: CreateRole(payload)
activate RoleService
RoleService->RoleService: Validate()

alt "Data not valid"
    RoleService-->RoleEndpoint: UnprocessableEntity
    RoleEndpoint-->RoleHTTPTransport: UnprocessableEntity
    RoleHTTPTransport-->Router: UnprocessableEntity
    Router-->AddRoleFormContainer: UnprocessableEntity
    AddRoleFormContainer-->AddRolePage: UnprocessableEntity
    AddRolePage-->Admin: UnprocessableEntity
else
    RoleService->RoleService: role := RoleModel()
    RoleService->RoleCommand: Create(role)
    activate RoleCommand
    RoleCommand-->RoleService: uuid
    deactivate RoleCommand
    RoleService->RoleQuery: Find(uuid)
    activate RoleQuery
    RoleQuery-->RoleService: role
    deactivate RoleQuery
    RoleService-->RoleEndpoint: role
    deactivate RoleService
    RoleEndpoint->RoleEndpoint: response := Response(role, nil)
    RoleEndpoint-->RoleHTTPTransport: response
    deactivate RoleEndpoint
    RoleHTTPTransport-->Router: response
    deactivate RoleHTTPTransport
    Router-->AddRoleFormContainer: response
    deactivate Router
    AddRoleFormContainer-->AddRolePage: response
    deactivate AddRoleFormContainer
    AddRolePage-->Admin: response
    deactivate AddRolePage
end

deactivate Admin

@enduml