@startuml DeletePoster

skinparam Monochrome true
skinparam Shadowing false
hide footbox

actor Caller
participant "Poster: Service" as PosterService
participant "Poster: Command" as PosterCommand
participant "Poster: Query" as PosterQuery

Caller->PosterService: DeleteByEvent(context, eventId)
PosterService->PosterQuery: Find(context, []SliceConditions)
PosterQuery-->PosterService: posters

alt "len(posters) < 1"
    PosterService-->Caller: false
else
    loop "for each posters"
        PosterService->PosterCommand: Delete(context, poster)
        PosterCommand-->PosterService: isDeleted
    end
    PosterService-->Caller: isDeleted
end

@enduml