@startuml DeleteMaterial

skinparam Monochrome true
skinparam Shadowing false
hide footbox

actor Caller
participant "Material: Service" as MaterialService
participant "Material: Command" as MaterialCommand
participant "Material: Query" as MaterialQuery

Caller->MaterialService: DeleteByClass(context, classId)
MaterialService->MaterialQuery: Find(context, []SliceConditions)
MaterialQuery-->MaterialService: materials

alt "len(materials) < 1"
    MaterialService-->Caller: false
else
    loop "for each materials"
        MaterialService->MaterialCommand: Delete(context, material)
        MaterialCommand-->MaterialService: isDeleted
    end
    MaterialService-->Caller: isDeleted
end

@enduml