@startuml DeleteUser

skinparam Monochrome true
skinparam Shadowing false
hide footbox

actor Admin
participant "Page: User" as UserPage
participant "Container: User Table" as UserTableContainer
participant "Component: User Table" as UserTable
participant "Service: User Service" as FEUserService
participant "Router" as Router
participant "User: HTTP Transport" as UserHTTPTransport
participant "User: Endpoint" as UserEndpoint
participant "User: Service" as UserService
participant "User: Command" as UserCommand
participant "User: Query" as UserQuery

activate Admin

Admin->UserPage: Open "Manage User" Page
UserPage->UserTableContainer: Render "User Table" Container
UserTableContainer->UserTable: Render "User Table"
UserTable-->UserTableContainer: rendered
UserTableContainer-->UserPage: rendered
UserPage-->Admin: rendered

Admin->UserPage: Mark "User"
UserPage->UserTableContainer: Mark "User"
UserTableContainer->UserTable: Mark "User"
UserTable-->UserTableContainer: marked
UserTableContainer-->UserPage: marked
UserPage-->Admin: marked

Admin->UserPage: Click "Delete Selected" Button
UserPage->UserTableContainer: showDeleteConfirmation(item)

alt "Cancel Delete"
    UserTableContainer-->UserPage: Close Dialog
    UserPage-->Admin: Close Dialog
else
    UserTableContainer->UserTableContainer: handleDeleteConfirmation(item)
    UserTableContainer->FEUserService: deleteUser(payload)
    FEUserService->Router: route("DELETE", "v2/users", formData)
    Router->UserHTTPTransport: DeleteUsers(UserService, []ServerOption)
    UserHTTPTransport->UserEndpoint: DeleteMany(UserService)
    UserEndpoint->UserService: DeleteUsers(context, []email)

    loop "for each uuid"
        UserService->UserQuery: GetPureModel(context, []SliceConditions])
        UserQuery-->UserService: user

        UserService->UserCommand: Delete(context, user)
        UserCommand-->UserService: isDeleted
    end

    UserService-->UserEndpoint: isDeleted
    UserEndpoint->UserEndpoint: response := Response(isDeleted, nil)
    UserEndpoint-->UserHTTPTransport: response
    UserHTTPTransport-->Router: response
    Router-->FEUserService: response
    FEUserService-->UserTableContainer: response
    UserTableContainer-->UserPage: response
    UserPage-->Admin: response
end

@enduml