@startuml GetClass_Member

skinparam Monochrome true
skinparam Shadowing false
hide footbox

actor Member
participant "Page: Class List" as ClassListPage
participant "Container: Class List" as ClassListContainer
participant "Component: Class Card" as ClassCard
participant "Service: Class Service" as FEClassService
participant "Router" as Router
participant "Class: HTTP Transport" as ClassHTTPTransport
participant "Class: Endpoint" as ClassEndpoint
participant "Class: Service" as ClassService
participant "Class: Command" as ClassCommand
participant "Class: Query" as ClassQuery

Member->ClassListPage: Open "Class List" Page
ClassListPage->ClassListContainer: fetchClassesByEventId()
ClassListContainer->FEClassService: fetchClassesByEventId(eventId)
FEClassService->Router: route("GET", "v2/event/{event_id}/classes")
Router->ClassHTTPTransport: FetchPaginatedClasss(ClassService, []ServerOption)
ClassHTTPTransport->ClassEndpoint: All(ClassService, withPaginated)
ClassEndpoint->ClassService: All(context, params)

alt "With Paginate"
    ClassService->ClassQuery: All(context, []SliceConditions, PaginateModel)
else
    ClassService->ClassQuery: All(context, []SliceConditions, nil)
end
ClassQuery-->ClassService: classes
ClassService-->ClassEndpoint: classes

opt "With Paginate"
    ClassEndpoint->ClassService: GetPagination(context, params)
    ClassService->ClassQuery: Count(context, []SliceConditions)
    ClassQuery-->ClassService: total
    ClassService-->ClassEndpoint: total
end

ClassEndpoint->ClassEndpoint: response := Response(classes, paginateMetadata)
ClassEndpoint-->ClassHTTPTransport: response
ClassHTTPTransport-->Router: response
Router-->FEClassService: response
FEClassService-->ClassListContainer: response
ClassListContainer->ClassCard: Render "Class Table"
ClassCard-->ClassListContainer: rendered
ClassListContainer-->ClassListPage: rendered
ClassListPage-->Member: rendered

@enduml