@startuml Logout

skinparam Monochrome true
skinparam Shadowing false
hide footbox

actor Employee
participant "Page: Profile" as ProfilePage
participant "Container: Profile Container" as ProfileContainer
participant "Service: Auth Service" as FEAuthService
participant "Router" as Router
participant "Session: HTTP Transport" as SessionHTTPTransport
participant "Session: Endpoint" as SessionEndpoint
participant "Session: Service" as SessionService
participant "User: Service" as UserService
participant "User: Query" as UserQuery
participant "Session: Command" as SessionCommand
participant "Session: Query" as SessionQuery

Employee->ProfilePage: Open "Profile" Page
ProfilePage-->Employee: response

Employee->ProfilePage: Click "Logout" Button
ProfilePage->ProfileContainer: handleLogout()
ProfileContainer->FEAuthService: logout()
FEAuthService->Router: route("POST", "v2/logout")
Router->SessionHTTPTransport: Logout(SessionService, []ServerOption)
SessionHTTPTransport->SessionEndpoint: Logout(SessionService)
SessionEndpoint->SessionService: Logout(context)
SessionService->SessionQuery: FindToken(context, token)
SessionQuery-->SessionService: session
SessionService->SessionCommand: Delete(context, session)
SessionCommand-->SessionService: isDeleted
SessionService-->SessionEndpoint: isDeleted
SessionEndpoint->SessionEndpoint: response := Response(user, nil)
SessionEndpoint-->SessionHTTPTransport: response
SessionHTTPTransport-->Router: response
Router-->FEAuthService: response
FEAuthService-->ProfileContainer: response
ProfileContainer-->ProfilePage: response
ProfilePage-->Employee: response

@enduml