@startuml SearchDivision

skinparam Monochrome true
skinparam Shadowing false
hide footbox

actor Admin
participant ":UserForm" as UserFormComponent
participant ":DivisionService (Frontend)" as FEDivisionService
participant ":Route" as Route
participant ":DivisionHTTPTransport" as DivisionHTTPTransport
participant ":DivisionEndpoint" as DivisionEndpoint
participant ":DivisionService" as DivisionService
participant ":DivisionQuery" as DivisionQuery

Admin->UserFormComponent: type search keyword
UserFormComponent->UserFormComponent: fetchDivisions()
UserFormComponent->FEDivisionService: fetchDivisions(page, limit, keyword)
UserFormComponent->Route: route("GET", "v2/divisions?search=role_to_search")
Route->DivisionHTTPTransport: FetchPaginatedDivisions(DivisionService, []ServerOption)
DivisionHTTPTransport->DivisionEndpoint: All(DivisionService, withPaginate)
DivisionEndpoint->DivisionService: All(context, params)

alt "With Paginate"
    DivisionService->DivisionQuery: All(context, []SliceConditions, PaginateModel)
else
    DivisionService->DivisionQuery: All(context, []SliceConditions, nil)
end

DivisionQuery-->DivisionService: roles
DivisionService-->DivisionEndpoint: roles

opt "With Paginate"
    DivisionEndpoint->DivisionService: GetPagination(context, PaginateModel)
    DivisionService->DivisionQuery: Count(context, []SliceConditions)
    DivisionQuery-->DivisionService: total
    DivisionService-->DivisionEndpoint: total
end

DivisionEndpoint->DivisionEndpoint: response := Response(roles, paginateMetadata)
DivisionEndpoint-->DivisionHTTPTransport: response
DivisionHTTPTransport-->Route: response
Route-->FEDivisionService: response
FEDivisionService-->UserFormComponent: response
UserFormComponent-->Admin: response

@enduml