@startuml UpdateRole

skinparam Monochrome true
skinparam Shadowing false
hide footbox

actor Admin
participant "Page: Edit Role" as EditRolePage
participant "Container: Edit Role Form" as EditRoleFormContainer
participant "Component: Role Form" as RoleForm
participant "Service: Role Service" as FERoleService
participant "Router" as Router
participant "Role: HTTP Transport" as RoleHTTPTransport
participant "Role: Endpoint" as RoleEndpoint
participant "Role: Service" as RoleService
participant "Role: RoleCommand" as RoleCommand
participant "Role: RoleQuery" as RoleQuery

Admin->EditRolePage: Open "Edit Role" Page
EditRolePage->EditRoleFormContainer: Render "Edit Role Form" Container
EditRoleFormContainer->RoleForm: Render "Role Form"
RoleForm-->EditRoleFormContainer: rendered
EditRoleFormContainer-->EditRolePage: rendered
EditRolePage-->Admin: rendered

Admin->EditRolePage: Fill Form
EditRolePage->EditRoleFormContainer: Fill Form
EditRoleFormContainer->RoleForm: Fill Form
RoleForm-->EditRoleFormContainer: form data
EditRoleFormContainer-->EditRolePage: form data
EditRolePage-->Admin: form data

Admin->EditRolePage: Click "Update Role" Button
EditRolePage->EditRoleFormContainer: handleRoleFormSubmitted()
EditRoleFormContainer->FERoleService: updateRole(id, payload)
FERoleService->Router: route("PUT", "v2/role/{role_id}", formData)
Router->RoleHTTPTransport: UpdateRole(RoleService, []ServerOption)
RoleHTTPTransport->RoleEndpoint: Update(RoleService, id)
RoleEndpoint->RoleService: UpdateRole(context, payload, id)
RoleService->RoleService: Validate()

alt "Data not valid"
    RoleService-->RoleEndpoint: UnprocessableEntity
    RoleEndpoint-->RoleHTTPTransport: UnprocessableEntity
    RoleHTTPTransport-->Router: UnprocessableEntity
    Router-->FERoleService: UnprocessableEntity
    FERoleService-->EditRoleFormContainer: UnprocessableEntity
    EditRoleFormContainer-->EditRolePage: UnprocessableEntity
    EditRolePage-->Admin: UnprocessableEntity
else
    RoleService->RoleQuery: Find(context, uuid)

    RoleQuery-->RoleService: role
    RoleService->RoleService: binding role data
    RoleService->RoleCommand: Update(context, role)

    RoleCommand-->RoleService: isUpdated
    RoleService-->RoleEndpoint: role
    RoleEndpoint->RoleEndpoint: response := Response(role, nil)
    RoleEndpoint-->RoleHTTPTransport: response
    RoleHTTPTransport-->Router: response
    Router-->FERoleService: response
    FERoleService-->EditRoleFormContainer: response
    EditRoleFormContainer-->EditRolePage: response
    EditRolePage-->Admin: response
end


@enduml