@startuml Upload

skinparam Monochrome true
skinparam Shadowing false

actor Caller
participant "Storage: GRPC Transport" as StorageGRPCTransport
participant "Storage: Service" as StorageService
participant "AWS: S3" as AWSS3

activate Caller

Caller->StorageGRPCTransport: Upload(ProtoBuffer)
activate StorageGRPCTransport
StorageGRPCTransport->StorageService: Upload(bytes)
activate StorageService
StorageService->StorageService: Validate()

alt "Data not valid"
    StorageService-->StorageGRPCTransport: GRPC_PRECONDITION_FAILED
    StorageGRPCTransport->Caller: GRPC_PRECONDITION_FAILED
else
    loop "For each file"
        StorageService->AWSS3: PutObject(PutObjectInput)
        activate AWSS3
        AWSS3-->StorageService: key, error
        deactivate AWSS3

        break "Any error"
            StorageService-->StorageGRPCTransport: GRPC_INTERNAL
            StorageGRPCTransport-->Caller: GRPC_INTERNAL
        end
    end
    StorageService-->StorageGRPCTransport: OK
    deactivate StorageService
    StorageGRPCTransport-->Caller: OK
    deactivate StorageGRPCTransport
end

deactivate Caller

@enduml