@startuml NOTIFICATION_SubscribeEventCreated

skinparam Monochrome true
skinparam Shadowing false
hide footbox

actor "Caller" as Caller
participant ":NotificationNATSTransport" as NotificationNATSTransport
participant ":NotificationService" as NotificationService
participant ":MessageService (Template Tag)" as MessageService

Caller->NotificationNATSTransport: eventCreatedSubscriber(conn, logger, notifService, messageService)

alt "Data Valid"
    NotificationNATSTransport->MessageService: GetCompileMessage(context, type, payload)
    MessageService-->NotificationNATSTransport: compiled message

    NotificationNATSTransport->NotificationService: Post(context, []payload)
    NotificationService-->NotificationNATSTransport: subscribed
    NotificationNATSTransport-->Caller: subscribed
else
    NotificationNATSTransport-->Caller: error
end

@enduml