@startuml NOTIFICATION_SubscribeCommitRequest

skinparam Monochrome true
skinparam Shadowing false
hide footbox

actor "Caller" as Caller
participant ":NotificationNATSTransport" as NotificationNATSTransport
participant ":NotificationService" as NotificationService
participant ":MessageService (Template Tag)" as MessageService

Caller->NotificationNATSTransport: requestUpdatedSubscriber(conn, logger, notifService, messageService)

alt "Data Valid"
    loop "for each requester"
        alt "status is Approved"
            NotificationNATSTransport->MessageService: GetCompiledMessage(context, type, payload)
            MessageService-->NotificationNATSTransport: compiled message
        else "status is Low Priority"
            NotificationNATSTransport->MessageService: GetCompiledMessage(context, type, payload)
            MessageService-->NotificationNATSTransport: compiled message
        else "status is Rejected"
            NotificationNATSTransport->MessageService: GetCompiledMessage(context, type, payload)
            MessageService-->NotificationNATSTransport: compiled message
        end
    end

    opt "there is approved"
        NotificationNATSTransport->NotificationService: Post(context, []payload)
        NotificationService-->NotificationNATSTransport: subscribed
    end

    opt "there is lowPriorities"
        NotificationNATSTransport->NotificationService: Post(context, []payload)
        NotificationService-->NotificationNATSTransport: subscribed
    end

    opt "there is rejected"
        NotificationNATSTransport->NotificationService: Post(context, []payload)
        NotificationService-->NotificationNATSTransport: subscribed
    end

    NotificationNATSTransport-->Caller: subscribed
else
    NotificationNATSTransport-->Caller: error
end

@enduml