@startuml DeleteMaterial

actor Caller
participant "Material: Service" as MaterialService
participant "Material: Command" as MaterialCommand
participant "Material: Query" as MaterialQuery

activate Caller

Caller->MaterialService: DeleteByClass(payload)
activate MaterialService
MaterialService->MaterialQuery: Find([]SliceConditions)
activate MaterialQuery
MaterialQuery-->MaterialService: materials
deactivate MaterialQuery

alt "len(materials) < 1"
    MaterialService-->Caller: false
else
    loop "for each materials"
        MaterialService->MaterialCommand: Delete(material)
        activate MaterialCommand
        MaterialCommand-->MaterialService: isDeleted
        deactivate MaterialCommand
    end
    MaterialService-->Caller: isDeleted
    deactivate MaterialService
end

deactivate Caller

@enduml