@startuml CreateMaterial

skinparam ConditionEndStyle hline
skinparam conditionStyle diamond
skinparam Monochrome true
skinparam Shadowing false

|Caller|
start
:Create Material;

|System|
:Validate Payload;
split
    -> VALID;
    :Insert Material data to Database;
    split
        -> CREATED;
        :Add Success Information;
    split again
        -> NOT CREATED;
        :Add Error Information;
    end split
split again
    -> NOT VALID;
    :Add Error Information;
end split
stop

@enduml