@startuml DeletePoster

skinparam Monochrome true
skinparam Shadowing false
hide footbox

actor Caller
participant ":PosterService" as PosterService
participant ":PosterCommand" as PosterCommand
participant ":PosterQuery" as PosterQuery

Caller->PosterService: DeleteByEvent(context, eventId)
PosterService->PosterQuery: Find(context, []SliceConditions)
PosterQuery-->PosterService: posters

alt "Poster Found"
    loop "for each posters"
        PosterService->PosterCommand: Delete(context, poster)
        PosterCommand-->PosterService: isDeleted
    end
    PosterService-->Caller: isDeleted
else
    PosterService-->Caller: false
end

@enduml