@startuml GetClass_Member

skinparam ConditionEndStyle hline
skinparam conditionStyle diamond
skinparam Monochrome true
skinparam Shadowing false

|Member|
start
:Open Class List Page;

|System|
:Get Class data from Database;
:Display the data to table;

stop

@enduml