@startuml UnbookingClass

skinparam ConditionEndStyle hline
skinparam conditionStyle diamond
skinparam Monochrome true
skinparam Shadowing false

|Admin|
start
:Open Attach Class List;

|System|
:Get Booked Room By Logged User;
:Display the data to List View;

|Admin|
:Hit Delete Button;

|System|
:Show Confirmation Dialog;

|Admin|
if (Agree Delete ?) then (No)
    :Close Dialog;
else (Yes)
    |System|
    :Delete Class from Database;
    split
        -> CREATED;
        :Delete Material from Database if Exist;
        :Add Success Information;
        :Publish Subject Based Message on Class Deleted;
    split again
        -> NOT CREATED;
        :Add Error Information;
    end split
endif
stop

@enduml