@startuml DeleteMaterial

skinparam Monochrome true
skinparam Shadowing false
hide footbox

actor Caller
participant ":MaterialService" as MaterialService
participant ":MaterialCommand" as MaterialCommand
participant ":MaterialQuery" as MaterialQuery

Caller->MaterialService: DeleteByClass(context, classId)
MaterialService->MaterialQuery: Find(context, []SliceConditions)
MaterialQuery-->MaterialService: materials

alt "Material Found"
    loop "for each materials"
        MaterialService->MaterialCommand: Delete(context, material)
        MaterialCommand-->MaterialService: isDeleted
    end
    MaterialService-->Caller: isDeleted
else
    MaterialService-->Caller: false
end

@enduml