@startuml CreateDivision

skinparam ConditionEndStyle hline
skinparam conditionStyle diamond
skinparam Monochrome true
skinparam Shadowing false

|Member, Admin|
start
:Open Add Division Page;
:Fill Division Form;
:Hit Create Division Button;

|System|
:Validate Payload;
split
    -> VALID;
    :Insert Division data to Database;
    split
        -> CREATED;
        :Add Success Information;
    split again
        -> NOT CREATED;
        :Add Error Information;
    end split
split again
    -> NOT VALID;
    :Add Error Information;
end split
stop

@enduml