@startuml CreateRoom

skinparam ConditionEndStyle hline
skinparam Monochrome true
skinparam Shadowing false

|Admin|
start
:Open "Add Room" Page;
:Fill "Room" Form;
:Hit "Create Room" Button;

|System|
:Validate Data;
if (Valid ?) then (Yes)
    :Insert "Room" data to Database;
    fork
        if (IsCreated ?) then (Yes)
            :Adding Success Information;
        else (No)
            :Adding Error Information;
        endif
    endfork
    stop
else (No)
    stop
endif
@enduml