@startuml CreateUser

skinparam ConditionEndStyle hline
skinparam conditionStyle diamond
skinparam Monochrome true
skinparam Shadowing false

|Admin|
start
:Open "Add User" Page;

|System|
:Get "Roles" data from Database;
:Get "Division" data from Database;
:Display fetched data into its own field;

|Admin|
:Fill "User" Form;

|Admin|
if (Search Role ?) then (Yes)
    |System|
    :Get "Role" data from Database;
    :Display fetched data into role field;
endif

|Admin|
if (Search Division ?) then (Yes)
    |System|
    :Get "Division" data from Database;
    :Display fetched data into division field;
endif

|Admin|
:Hit "Create User" Button;

|System|
:Validate Data;
if (Valid ?) then (Yes)
    :Insert "User" data to Database;
    if (IsCreated ?) then (Yes)
        :Adding Success Information;
        :Publish Subject Based Message on User Created;
    else (No)
        :Adding Error Information;
    endif
else (No)
endif
stop

@enduml