@startuml CreateShift

skinparam ConditionEndStyle hline
skinparam conditionStyle diamond
skinparam Monochrome true
skinparam Shadowing false

|Admin|
start
:Open "Add Shift" Page;
:Fill "Shift" Form;
:Hit "Create Shift" Button;

|System|
:Validate Data;
if (Valid ?) then (Yes)
    :Insert "Shift" data to Database;
    if (IsCreated ?) then (Yes)
        :Adding Success Information;
    else (No)
        :Adding Error Information;
    endif
else (No)
endif
stop

@enduml