@startuml CreateClass

skinparam ConditionEndStyle hline
skinparam Monochrome true
skinparam Shadowing false

|Admin|
start
:Open "Add Class" Page;
:Fill "Class" Form;
:Hit "Create Class" Button;

|System|
:Validate Data;
if (Valid ?) then (Yes)
    :Check the Class is Valid on Transaction;

    if (Valid ?) then (Yes)

        :Insert "Class" data to Database;
        if (IsCreated ?) then (Yes)
            if (Has Material ?) then (Yes)
                :Zip Materials;
                :Upload Zipped Material;
                :Insert "Material" data to Database;
            endif
            :Adding Success Information;
            :Publish Subject Based Message on Class Created;
        else (No)
            :Adding Error Information;
        endif
    else (No)
    endif
    stop
else (No)
    stop
endif

@enduml