@startuml DeleteShift

skinparam ConditionEndStyle hline
skinparam conditionStyle diamond
skinparam Monochrome true
skinparam Shadowing false

|Admin|
start
:Open "Manage Shift" Page;

|System|
:Get "Shift" data from Database;
:Display the data to table;

|Admin|
:Mark "Shift" to Delete;
:Hit "Delete Selected" Button;

|System|
:Show Confirmation Dialog;

|Admin|
if (Agree Delete ?) then (No)
    :Show Dialog;
else (Yes)
    |System|
    while(For each shift) is (Has Shift)
        :Delete "Shift" from Database;
        |System|
        if (Is Deleted ?) then (Yes)
            :Adding Success Information;
        else (No)
            :Adding Error Information;
        endif
    endwhile
endif
stop

@enduml