@startuml DeleteClass

skinparam ConditionEndStyle hline
skinparam Monochrome true
skinparam Shadowing false

|Admin|
start
:Open "Detail Class" Page;

|System|
:Get "Class" data from Database;
:Display then data to table;

|Admin|
:Hit "Delete" Button;

|System|
:Show Confirmation Dialog;

|Admin|
if (Agree Delete ?) then (No)
    stop
else (Yes)
    |System|
    while (For each uuid) is (uuid)
        :Delete "Class" from Database;
        fork
            |System|
            if (Is Deleted ?) then (Yes)
                :Delete Related Material if Exists;
                :Adding Success Information;
                :Publish Subject Based Message on Class Deleted;
            else (No)
                :Adding Error Information;
            endif
        endfork
    endwhile
    stop
endif
@enduml