@startuml DeleteRoom

skinparam ConditionEndStyle hline
skinparam conditionStyle diamond
skinparam Monochrome true
skinparam Shadowing false

|Admin|
start
:Open "Manage Room" Page;

|System|
:Get "Room" data from Database;
:Display then data to table;

|Admin|
:Mark "Room" to Delete;
:Hit "Delete Selected" Button;

|System|
:Show Confirmation Dialog;

|Admin|
if (Agree Delete ?) then (No)
else (Yes)
    |System|
    while(For each room) is (Has Room)
        :Delete "Room" from Database;
        |System|
        if (Is Deleted ?) then (Yes)
            :Adding Success Information;
        else (No)
            :Adding Error Information;
        endif
    endwhile
endif
stop

@enduml