@startuml DeleteUser

skinparam ConditionEndStyle hline
skinparam conditionStyle diamond
skinparam Monochrome true
skinparam Shadowing false

|Admin|
start
:Open "Manage User" Page;

|System|
:Get "User" data from Database;
:Display the data to table;

|Admin|
:Mark "User" to Delete;
:Hit "Delete Selected" Button;

|System|
:Show Confirmation Dialog;

|Admin|
if (Agree Delete ?) then (No)
else (Yes)
    |System|
    :Delete "User" from Database;
    if (Is Deleted ?) then (Yes)
        :Adding Success Information;
        :Publish Subject Based Message on User Deleted;
    else (No)
        :Adding Error Information;
    endif
endif
stop

@enduml