@startuml DeleteUserETL

skinparam ConditionEndStyle hline
skinparam conditionStyle diamond
skinparam Monochrome true
skinparam Shadowing false

|Caller|
start
:Delete Replica;

|System|
:Delete "User" from Database;

fork
    |System|
    if (Is Deleted ?) then (Yes)
        :Adding Success Information;
    else (No)
        :Adding Error Information;
    endif
endfork

stop
@enduml