@startuml DeleteShift

skinparam ConditionEndStyle hline
skinparam Monochrome true
skinparam Shadowing false

|Admin|
start
:Open "Manage Shift" Page;

|System|
:Get "Shift" data from Database;
:Display then data to table;

|Admin|
:Mark "Shift" to Delete;
:Hit "Delete Selected" Button;

|System|
:Show Confirmation Dialog;

|Admin|
if (Agree Delete ?) then (No)
    stop
else (Yes)
    |System|
    :Delete "Shift" from Database;
    fork
        |System|
        if (Is Deleted ?) then (Yes)
            :Adding Success Information;
        else (No)
            :Adding Error Information;
        endif
    endfork
    stop
endif
@enduml