@startuml EVENT_SubscribeRTCreated

skinparam ConditionEndStyle hline
skinparam conditionStyle diamond
skinparam Monochrome true
skinparam Shadowing false

|Caller|
start
:Subscribe Transaction.TransactionCreated;

|System|
:Create Replica Room Transaction to RoomTransactionETL;
if (Is Error ?) then (Yes)
    :Adding Error Information;
endif
stop

@enduml