@startuml EVENT_SubscribeUserDeleted

skinparam ConditionEndStyle hline
skinparam conditionStyle diamond
skinparam Monochrome true
skinparam Shadowing false

|Caller|
start
:Subscribe User.UserDeleted;

|System|
:Parsing Event Message;

if (Valid ?) then (Yes)
    :Delete Replica User from UserETL;

    if (Is Error ?) then (Yes)
        :Adding Error Information;
    endif
else (No)
endif
stop

@enduml