@startuml EVENT_SubscribeUserCreated

skinparam ConditionEndStyle hline
skinparam conditionStyle diamond
skinparam Monochrome true
skinparam Shadowing false

|Caller|
start
:Subscribe User.UserCreated;

|System|
:Parsing Event Message;

if (Valid ?) then (Yes)
    :Create Replica User to UserETL;

    if (Is Error ?) then (Yes)
        :Adding Error Information;
    endif
else (No)
endif
stop

@enduml