@startuml EVENT_SubscribeRTCreated

skinparam ConditionEndStyle hline
skinparam Monochrome true
skinparam Shadowing false

|Caller|
start

:Subscribe Transaction.TransactionCreated;

|System|
:Parsing Event Message;

if (Valid ?) then (Yes)
    :Create Replica Room Transaction to RoomTransactionETL;

    if (Is Error ?) then (Yes)
        :Adding Error Information;
    endif
    
    stop
else (No)
    stop
endif

@enduml