@startuml EVENT_SubscribeUserCreated

skinparam ConditionEndStyle hline
skinparam conditionStyle diamond
skinparam Monochrome true
skinparam Shadowing false

|Caller|
start
:Subscribe User.UserCreated;

|System|
:Create Replica User to UserETL;

if (Is Error ?) then (Yes)
    :Adding Error Information;
endif
stop

@enduml