@startuml TRANSACTION_SubscribeRTDeleted

skinparam ConditionEndStyle hline
skinparam conditionStyle diamond
skinparam Monochrome true
skinparam Shadowing false

|Caller|
start
:Subscribe Transaction.TransactionDeleted;

|System|
:Delete Replica Room Transaction from RoomTransactionETL;

if (Is Error ?) then (Yes)
    :Adding Error Information;
endif
stop

@enduml