@startuml GetShiftAvailability

skinparam ConditionEndStyle hline
skinparam Monochrome true
skinparam Shadowing false

|Admin|
start
:Open "Class" Form;
:Fill "Date" Field;

|System|
:Get "Available Shift" data from Database;
:Display then data to Shift field;

stop

@enduml