@startuml TRANSACTION_SubscribeClassCreated

skinparam ConditionEndStyle hline
skinparam conditionStyle diamond
skinparam Monochrome true
skinparam Shadowing false

|Caller|
start
:Subscribe Class.ClassCreated;

|System|
:Create Room Transaction;

if (Is Error ?) then (Yes)
    :Adding Error Information;
endif
stop

@enduml