@startuml UpdateRoom

skinparam ConditionEndStyle hline
skinparam conditionStyle diamond
skinparam Monochrome true
skinparam Shadowing false

|Admin|
start
:Open "Edit Room" Page;

|System|
:Get Selected "Room" data from Database;
:Display then data to its field;

|Admin|
:Change form data;
:Hit "Edit Room" Button;

|System|
:Validate;

if (Valid ?) then (Yes)
    :Update "Room" data from Database;
    if (IsUpdated ?) then (Yes)
        :Adding Success Information;
    else (No)
        :Adding Error Information;
    endif
else (No)
endif
stop

@enduml