@startuml UpdateShift

skinparam ConditionEndStyle hline
skinparam conditionStyle diamond
skinparam Monochrome true
skinparam Shadowing false

|Admin|
start
:Open "Edit Shift" Page;

|System|
:Get Selected "Shift" data from Database;
:Display the data to its field;

|Admin|
:Change form data;
:Hit "Edit Shift" Button;

|System|
:Validate;

if (Valid ?) then (Yes)
    :Update "Shift" data from Database;
    if (IsUpdated ?) then (Yes)
        :Adding Success Information;
    else (No)
        :Adding Error Information;
    endif
else (No)
endif
stop

@enduml