@startuml MAILER_SubscribeEventCreated

skinparam Monochrome true
skinparam Shadowing false
hide footbox

actor "Caller" as Caller
participant "Mailer: NATS Transport" as MailerNATSTransport
participant "Mailer: Mailer Service" as MailerService
participant "Template Tag CMS: HTTP Transport" as CMSHTTPTransport
participant "Messenger: HTTP Transport" as MessengerHTTPTransport

activate Caller

Caller->MailerNATSTransport: Subscribe Event.EventCreated
activate MailerNATSTransport
MailerNATSTransport->MailerNATSTransport: Parse Event Message

alt "Data Not Valid"
    MailerNATSTransport-->Caller: panic
else
    alt "Is Broadcast"
        MailerNATSTransport->MailerService: build template tag payload
        activate MailerService
        MailerService->CMSHTTPTransport: GetCompileMessage(payload)
        activate CMSHTTPTransport
        CMSHTTPTransport-->MailerService: compiled message
        deactivate CMSHTTPTransport
        MailerService->MessengerHTTPTransport: SendEmail(receiver, subject, compiledMessage)
        activate MessengerHTTPTransport
        MessengerHTTPTransport-->MailerService: subscribed
        deactivate MessengerHTTPTransport
        MailerService-->MailerNATSTransport: subscribed
        deactivate MailerService
        MailerNATSTransport-->Caller: subscribed
    else
        MailerNATSTransport-->Caller: subscribed
        deactivate MailerNATSTransport
    end
end

deactivate Caller

@enduml