@startuml NOTIFICATION_SubscribeEventCreated

skinparam Monochrome true
skinparam Shadowing false
hide footbox

actor "Caller" as Caller
participant "Notification: NATS Transport" as NotificationNATSTransport
participant "Notification: Service" as NotificationService
participant "Message: Service" as MessageService

activate Caller

Caller->NotificationNATSTransport: eventCreatedSubscriber(conn, logger, notifService, messageService)

alt "Data Not Valid"
    NotificationNATSTransport-->Caller: panic
else
    NotificationNATSTransport->MessageService: GetCompileMessage(context, type, payload)
    MessageService-->NotificationNATSTransport: compiled message

    NotificationNATSTransport->NotificationService: Post(context, []payload)
    NotificationService-->NotificationNATSTransport: subscribed
    NotificationNATSTransport-->Caller: subscribed
end

@enduml