@startuml PublishEventCreated

skinparam ConditionStyle hline
skinparam Monochrome true
skinparam Shadowing false
hide footbox

actor Caller
participant "Fazzlearning Kit: Event" as FazzlearningKitEvent
participant "Nats Streaming" as NatsStreaming

activate Caller

Caller->FazzlearningKitEvent: GetGlobalPublisher()
activate FazzlearningKitEvent
FazzlearningKitEvent-->Caller: publisher
Caller->FazzlearningKitEvent: Store(StoreDetail)
FazzlearningKitEvent->NatsStreaming: Publish(Requests.RequestUpdated, []byte)
activate NatsStreaming
NatsStreaming-->FazzlearningKitEvent: published
deactivate NatsStreaming
deactivate FazzlearningKitEvent
FazzlearningKitEvent-->Caller: published

deactivate Caller

@enduml