@startuml PublishEventCreated

skinparam ConditionStyle hline
skinparam Monochrome true
skinparam Shadowing false
hide footbox

actor Caller
participant "Fazzlearning Kit: Event" as FazzlearningKitEvent
participant "Nats Streaming" as NatsStreaming

Caller->FazzlearningKitEvent: GetGlobalPublisher()
FazzlearningKitEvent-->Caller: publisher
Caller->FazzlearningKitEvent: Store(StoreDetail)
FazzlearningKitEvent->NatsStreaming: Publish(Event.EventCreated, []byte)
NatsStreaming-->FazzlearningKitEvent: published
FazzlearningKitEvent-->Caller: published

@enduml