@startuml ReadNotification

skinparam Monochrome true
skinparam Shadowing false
hide footbox

actor Member
participant "Page: Notification Detail" as NotificationDetailPage
participant "Container: Notification Detail" as NotificationContainer
participant "Service: Notification Service" as FENotificationService
participant "Router" as Router
participant "Notification: HTTP Transport" as NotificationHTTPTransport
participant "Notification: Endpoint" as NotificationEndpoint
participant "Notification: Service" as NotificationService
participant "Notification: Query" as NotificationQuery
participant "Notification: Command" as NotificationCommand

Member->NotificationDetailPage: Open "Notification Detail" Pages
NotificationDetailPage->NotificationContainer: markNotificationAsRead()
NotificationContainer->FENotificationService: readNotif(notifId)
FENotificationService->Router: router("PATCH", "v2/notification/{notif_id}")
Router->NotificationHTTPTransport: Read(NotificationService, []ServerOption)
NotificationHTTPTransport->NotificationEndpoint: Read(NotificationService)
NotificationEndpoint->NotificationService: Read(context, payload)

NotificationService->NotificationQuery: Find(context, []SliceCondition)
NotificationQuery-->NotificationService: notification

NotificationService->NotificationCommand: Update(context, notif)
NotificationCommand-->NotificationService: is updated

NotificationService-->NotificationEndpoint: is updated
NotificationEndpoint->NotificationEndpoint: response := Response(isUpdated, nil)
NotificationEndpoint-->NotificationHTTPTransport: response
NotificationHTTPTransport-->Router: response
Router-->FENotificationService: response
FENotificationService-->NotificationContainer: response
NotificationContainer-->NotificationDetailPage: response
NotificationDetailPage-->Member: response

@enduml