@startuml PublishEventCreated

skinparam ConditionStyle hline
skinparam Monochrome true
skinparam Shadowing false
hide footbox

actor Caller
participant ":FazzlearningKitEvent" as FazzlearningKitEvent
participant ":NatsStreaming" as NatsStreaming

Caller->FazzlearningKitEvent: GetGlobalPublisher()
FazzlearningKitEvent-->Caller: publisher
Caller->FazzlearningKitEvent: Store(StoreDetail)
FazzlearningKitEvent->NatsStreaming: Publish(Requests.RequestUpdated, []byte)
NatsStreaming-->FazzlearningKitEvent: published
FazzlearningKitEvent-->Caller: published

@enduml