@startuml ClassSubSystem

left to right direction

skinparam Monochrome true
skinparam Shadowing false
skinparam packageStyle rectangle

actor Admin

rectangle "Class System" {
    Admin --> (Create Class)
    Admin --> (Delete Class)
    Admin --> (Booking Class)
    Admin --> (Unbooking Class)

    (Create Class) ..> (Publish Class Created) : include
    (Delete Class) ..> (Publish Class Deleted) : include

    (Booking Class) ..> (Create Class) : include
    (Unbooking Class) ..> (Delete Class) : include
}

@enduml