@startuml RoomTransactionSubSystem

left to right direction

skinparam Monochrome true
skinparam Shadowing false
skinparam packageStyle rectangle

actor Caller

rectangle "Room Transaction System" {
    (Caller) --> (Create Transaction)
    (Caller) --> (Delete Transaction)
    (Caller) --> (Check Validity of Transaction)

    (Create Transaction) ..> (Publish Transaction Created) : include
    (Delete Transaction) ..> (Publish Transaction Updated) : include
}

@enduml