@startuml NotificationSubSystem

left to right direction

skinparam Monochrome true
skinparam Shadowing false
skinparam packageStyle rectangle

actor Caller
actor Member

rectangle "Notification System" {
    Caller --> (Subscribe Event Created)
    Caller --> (Subscribe Commit Request)
    
    (Subscribe Event Created) ..> (Post Notification) : include
    (Subscribe Commit Request) ..> (Post Notification) : include

    Member --> (Read Notification)
    Member --> (Get Notification)
}

@enduml