@startuml RoleSubSystem

left to right direction

skinparam Monochrome true
skinparam Shadowing false
skinparam packageStyle rectangle

actor Admin

rectangle "Role System" {
    Admin --> (Create Role)
    Admin --> (Update Role)
    Admin --> (Delete Role)
    Admin --> (Get Role)
    Admin --> (Search Role)

    Member --> (Search Role)
}

@enduml