@startuml RoomTransactionETLSubSystem

left to right direction

skinparam Monochrome true
skinparam Shadowing false
skinparam packageStyle rectangle

actor System

rectangle "Room Transaction System" {
    System --> (Subscribe Room Transaction Created)
    System --> (Subscribe Room Transaction Deleted)

    (Subscribe Room Transaction Created) ..> (Create Replica) : include
    (Subscribe Room Transaction Deleted) ..> (Delete Replica) : include
}

@enduml