@startuml SubscribeClassDeleted

skinparam ConditionStyle hline
skinparam Monochrome true
skinparam Shadowing false
hide footbox

actor Caller
participant ":RoomTransactionNATSTransport" as RoomTransactionNATSTransport
participant ":RoomTransactionService" as RoomTransactionService


Caller->RoomTransactionNATSTransport: classDeletedSubscriber
RoomTransactionNATSTransport->RoomTransactionNATSTransport: parse message
RoomTransactionNATSTransport->RoomTransactionService: Delete(context, TransactionClass)
RoomTransactionService-->RoomTransactionNATSTransport: subscribed
RoomTransactionNATSTransport-->Caller: subscribed


@enduml