@startuml EventSubSystem

left to right direction

skinparam Monochrome true
skinparam Shadowing false
skinparam packageStyle rectangle

actor Admin

rectangle "Event System" {
    Admin --> (Create Event)
    
    (Create Event) ..> (Publish Subject Based Message on Event Created) : include
}

@enduml