@startuml FavouriteSubSystem

left to right direction

skinparam Monochrome true
skinparam Shadowing false
skinparam packageStyle rectangle

actor Member

rectangle "Favourite System" {
    Member --> (Like)
    Member --> (Unlike)
    Member --> (Get Favourite)
}

@enduml