@startuml MailerSubSystem

left to right direction

skinparam Monochrome true
skinparam Shadowing false
skinparam packageStyle rectangle

actor Caller

rectangle "Mailer System" {
    Caller --> (Subscribe Event Created)
    Caller --> (Subscribe Commit Request)
    (Subscribe Event Created) ..> (Send Email) : include
    (Subscribe Commit Request) ..> (Send Email) : include
}

@enduml