@startuml MailerSubSystem

left to right direction

skinparam Monochrome true
skinparam Shadowing false
skinparam packageStyle rectangle

actor Caller

rectangle "Mailer System" {
    Caller --> (Subscribe Event Created)
    Caller --> (Subscribe Commit Request)

    (Subscribe Event Created) ..> (Announce Event Created) : include
    (Subscribe Commit Request) ..> (Announce Request) : include
    
    (Announce Event Created) ..> (Send Email) : include
    (Announce Request) ..> (Send Email) : include
}

@enduml