@startuml RequesterSubSystem

left to right direction

skinparam Monochrome true
skinparam Shadowing false
skinparam packageStyle rectangle

actor Admin

rectangle "Requester System" {
    Admin --> (Commit Request)
    
    (Commit Request) ..> (Publish Subject Based Message on Commit Request) : include
}

@enduml