@startuml AttendanceSubSystem

left to right direction

skinparam Monochrome true
skinparam Shadowing false
skinparam packageStyle rectangle

actor Member

rectangle "Attendance System" {
    Member --> (Confirm Attendance)

    (Confirm Attendance) ..> (Create Attendance) : include
}

@enduml