@startuml RequesterSubSystem

left to right direction

skinparam Monochrome true
skinparam Shadowing false
skinparam packageStyle rectangle

actor Admin
actor Member

rectangle "Requester System" {
    Member --> (Register)
    Admin --> (Get Requester)
    
    Member --> (Cancel Register)
    Admin --> (Commit Request)
    Member --> (Get Requested)

    (Commit Request) ..> (Create Attendance) : extends
}

@enduml