@startuml CreateRole

skinparam ConditionEndStyle hline
skinparam conditionStyle diamond
skinparam Monochrome true
skinparam Shadowing false

|Admin|
start
:Open Add Role Page;
:Fill Role Form;
:Hit Create Role Button;

|System|
:Validate Payload;
split
    -> VALID;
    :Insert Role data to Database;
    split
        -> CREATED;
        :Add Success Information;
    split again
        -> NOT CREATED;
        :Add Error Information;
    end split
split again
    -> NOT VALID;
    :Add Error Information;
end split
stop

@enduml