@startuml DeleteRole

skinparam ConditionEndStyle hline
skinparam conditionStyle diamond
skinparam Monochrome true
skinparam Shadowing false

|Admin|
start
:Open Manage Role Page;

|System|
:Get Role data from Database;
:Display the data to table;

|Admin|
:Mark Role to Delete;
:Hit Delete Selected Button;

|System|
:Show Confirmation Dialog;

|Admin|
if (Agree Delete ?) then (No)
    :Close Dialog;
else (Yes)
    |System|
    :Delete Selected Role from Database;
    split
        -> DELETED;
        :Add Success Information;
    split again
        -> NOT DELETED;
        :Add Error Information;
    end split
endif
stop

@enduml