@startuml UpdateRole

skinparam ConditionEndStyle hline
skinparam conditionStyle diamond
skinparam Monochrome true
skinparam Shadowing false

|Admin|
start
:Open Edit Role Page;

|System|
:Get Selected Role data from Database;
:Display the data to its field;

|Admin|
:Change form data;
:Hit Edit Role Button;

|System|
:Validate Payload;
split
    -> VALID;
    :Update Role data from Database;
    split
        -> UPDATED;
        :Add Success Information;
    split again
        -> NOT UPDATED;
        :Add Error Information;
    end split
split again
    -> NOT VALID;
    :Add Error Information;
end split
stop

@enduml