@startuml CreateDivision

skinparam ConditionEndStyle hline
skinparam Monochrome true
skinparam Shadowing false

|Member,Admin|
start
:Open "Add Division" Page;
:Fill "Division" Form;
:Hit "Create Division" Button;

|System|
:Validate Data;
if (Valid ?) then (Yes)
    :Insert "Division" data to Database;
    fork
        if (IsCreated ?) then (Yes)
            :Adding Success Information;
        else (No)
            :Adding Error Information;
        endif
    endfork
    stop
else (No)
    stop
endif
@enduml