@startuml CreateMaterial

skinparam ConditionEndStyle hline
skinparam Monochrome true
skinparam Shadowing false

|Caller|
start
:Create Material;

|System|
:Validate Data;
if (Valid ?) then (Yes)
    while (for each materialLink) is (has link)
        :Insert "Material" data to Database;
        if (Is Created ?) then (Yes)
            :Adding Success Information;
        else (No)
            :Adding Error Information;
        endif
    endwhile
    stop
else (No)
    stop
endif

@enduml