@startuml DeleteDivision

skinparam ConditionEndStyle hline
skinparam conditionStyle diamond
skinparam Monochrome true
skinparam Shadowing false

|Admin|
start
:Open "Manage Division" Page;

|System|
:Get "Division" data from Database;
:Display then data to table;

|Admin|
:Mark "Division" to Delete;
:Hit "Delete Selected" Button;

|System|
:Show Confirmation Dialog;

|Admin|
if (Agree Delete ?) then (No)
    stop
else (Yes)
    |System|
    while(For each divisions) is (Has Division)
        :Delete "Division" from Database;
        fork
            |System|
            if (Is Deleted ?) then (Yes)
                :Adding Success Information;
            else (No)
                :Adding Error Information;
            endif
        endfork
    endwhile
    stop
endif
@enduml