@startuml DeleteEvent

skinparam ConditionEndStyle hline
skinparam conditionStyle diamond
skinparam Monochrome true
skinparam Shadowing false

|Admin|
start
:Open "Manage Event" Page;

|System|
:Get "Event" data from Database;
:Display then data to table;

|Admin|
:Hit "View Detail" Button;

|System|
:Get selected "Event" data from Database;
:Display then data to design given;

|Admin|
:Hit "Delete" Button;

|System|
:Show Confirmation Dialog;

|Admin|
if (Agree Delete ?) then (No)
    stop
else (Yes)
    |System|
    :Delete "Event" from Database;
    fork
        |System|
        if (Is Deleted ?) then (Yes)
            :Delete Related Poster if Exists;
            :Delete Related Class if Exists;
            :Adding Success Information;
        else (No)
            :Adding Error Information;
        endif
    endfork
    stop
endif
@enduml