@startuml GetClass_Admin

skinparam ConditionEndStyle hline
skinparam Monochrome true
skinparam Shadowing false

|Admin|
start
:Open "Event Detail" Page;

|System|
:Get "Class" data from Database;
:Display then data to table;

stop

@enduml