@startuml GetEvent_Admin

skinparam ConditionEndStyle hline
skinparam Monochrome true
skinparam Shadowing false

|Admin|
start
:Open "Manage Event" Page;

|System|
:Get "Event" data from Database;
:Display then data to table;

stop

@enduml