@startuml Login

skinparam ConditionEndStyle hline
skinparam Monochrome true
skinparam Shadowing false

|Admin,Member|
start
:Open "Login" Page;
:Choose "G-Suite" Account;

|System|
:Validate;

if (Valid ?) then (Yes)
    :Get User based on Account given;

    if (Data Found ?) then (Yes)
        :Generate Session Token;
        if (Generated ?) then (Yes)
            :Insert Session Data to Database;
        else (No)
            Stop
        endif
    else (No)
        stop
    endif
else (No)
    stop
endif

@enduml