@startuml Register

skinparam ConditionEndStyle hline
skinparam conditionStyle diamond
skinparam Monochrome true
skinparam Shadowing false

|Member|
start
:Open "Fulfilment" Page;

|System|
:Get "Division" data from Database;
:Display the data to its field;

|Member|
:Fill "Division Fulfilment" Form;
:Hit "Next" Button;

:Fill "Indentity Fulfilment" Form;
:Hit "Next" Button;

:Hit "Complete" Button;

|System|
:Validate;

if (Valid ?) then (Yes)
    if (Source is WEB ?) then (Yes)
        :Get "User" from Database;
    else (No)
        :Get "User" from Database;

        if (DeletedAt of User is not empty) then (Yes)
            :Set DeletedAt of "User" into NULL;
            :Update "User" from Database;
        else (No)
            :Register the "User" to Database;
        endif
    endif
else (No)
endif

if (User Not Found) then (Yes)
    :Adding "Error" Information;
else (No)
    :Generate User Token;
    :Create "Session" data to the Database;
endif

stop

@enduml