@startuml Register

skinparam ConditionEndStyle hline
skinparam conditionStyle diamond
skinparam Monochrome true
skinparam Shadowing false

|Member|
start
:Open "Fulfilment" Page;


|System|
:Get "Roles" data from Database;
:Get "Division" data from Database;
:Display fetched data into its own field;

|Member|
:Fill "Fulfilment" Form;
:Hit "Complete" Button;

|System|
:Validate;

if (Valid ?) then (Yes)
    :Insert User Data to Database;
    if (IsCreated ?) then (Yes)
        :Adding Success Information;
    else (No)
        :Adding Error Information;
    endif
else (No)
endif
stop

@enduml