@startuml Resolve

skinparam ConditionEndStyle hline
skinparam conditionStyle diamond
skinparam Monochrome true
skinparam Shadowing false

|Caller|
start
:Resolve URL;

|System|
:Resolve URL Given;
:GetObjectRequest to AWS S3;
if (Any Error ?) then (No)
    :Adding Resolved URL Information;
else (Yes)
    :Adding Error Information;
endif
stop

@enduml