@startuml SearchRole

skinparam ConditionEndStyle hline
skinparam conditionStyle diamond
skinparam Monochrome true
skinparam Shadowing false

|Admin|
start
:Search Role by Keyword;

|System|
:Get "Role" data by Keyword from Database;
:Display the data to its field;
stop

@enduml