@startuml UpdateEvent

skinparam ConditionEndStyle hline
skinparam conditionStyle diamond
skinparam Monochrome true
skinparam Shadowing false

|Admin|
start
:Open "Edit Event" Page;

|System|
:Get Selected "Event" data from Database;
:Display the data to its field;

|Admin|
:Change "Event" Form;
:Hit "Edit Event" Button;

|System|
:Validate Data;
if (Valid ?) then (Yes)
    :Update "Event" data from Database;
    if (IsUpdated ?) then (Yes)
        :Adding Success Information;
    else (No)
        :Adding Error Information;
    endif
else (No)
endif
stop

@enduml