@startuml UpdateRole

skinparam ConditionEndStyle hline
skinparam conditionStyle diamond
skinparam Monochrome true
skinparam Shadowing false

|Admin|
start
:Open "Edit Role" Page;

|System|
:Get Selected "Role" data from Database;
:Display then data to its field;

|Admin|
:Change form data;
:Hit "Edit Role" Button;

|System|
:Validate;

if (Valid ?) then (Yes)
    :Update "Role" data from Database;
    fork
        if (IsUpdated ?) then (Yes)
            :Adding Success Information;
        else (No)
            :Adding Error Information;
        endif
    endfork
    stop
else (No)
    stop
endif
@enduml