@startuml UpdateClass

skinparam ConditionEndStyle hline
skinparam conditionStyle diamond
skinparam Monochrome true
skinparam Shadowing false

|Admin|
start
:Open "Edit Class" Page;

|System|
:Get Selected "Class" data from Database;
:Display the data to its field;

|Admin|
:Change "Class" Form;
:Hit "Edit Class" Button;

|System|
:Validate Data;
if (Valid ?) then (Yes)
    :Update "Class" data from Database;
    if (IsUpdated ?) then (Yes)
        :Adding Success Information;
    else (No)
        :Adding Error Information;
    endif
else (No)
endif
stop

@enduml