@startuml Upload

skinparam ConditionEndStyle hline
skinparam conditionStyle diamond
skinparam Monochrome true
skinparam Shadowing false

|Caller|
start
:Upload File;

|System|
:Validate Data;
if (Valid ?) then (Yes)
    while(For each file) is (Has file)
        :PutObject into AWS S3;
    endwhile
    :Adding ObjectKey Information;
else (No)
endif
stop

@enduml