@startuml CreateUserETL

skinparam ConditionEndStyle hline
skinparam conditionStyle diamond
skinparam Monochrome true
skinparam Shadowing false

|Caller|
start
:Create Replica;

|System|
:Insert User ETL data to Database;
split
    -> CREATED;
    :Add Success Information;
split again
    -> NOT CREATED;
    :Add Error Information;
end split
stop

@enduml