@startuml DeleteUserETL

skinparam ConditionEndStyle hline
skinparam conditionStyle diamond
skinparam Monochrome true
skinparam Shadowing false

|Caller|
start
:Delete Replica;

|System|
:Delete User ETL from Database;
split
    -> DELETED;
    :Add Success Information;
split again
    -> NOT DELETED;
    :Add Error Information;
end split
stop

@enduml