@startuml PublishRoomTransactionDeleted

skinparam ConditionEndStyle hline
skinparam conditionStyle diamond
skinparam Monochrome true
skinparam Shadowing false

|Caller|
start
:Publish Room Transaction Deleted;

|Fazzlearning Kit|
:Get Global Publisher;
:Store Event on Stream;

|Nats Streaming|
:Publish;
stop
@enduml