@startuml TRANSACTION_SubscribeClassCreated

skinparam ConditionEndStyle hline
skinparam conditionStyle diamond
skinparam Monochrome true
skinparam Shadowing false

|Caller|
start
:Subscribe Class.ClassCreated;

|System|
:Create Room Transaction;
split
    -> SUCCESS;
    goto END
split again
    -> FAILED;
    :Add Error Information;
end split
label END
stop

@enduml