@startuml CancelRequestedClass

skinparam ConditionEndStyle hline
skinparam conditionStyle diamond
skinparam Monochrome true
skinparam Shadowing false

|Member|
start
:Open "Ticket Detail" Page;
:Click "Cancel" Button;

|System|
:Validate;

if (Data Valid ?) then (Yes)
    :Delete "Requester" data from Database;

    if (Valid ?) then (Yes)
        :Add Success Information;
    else (No)
        :Add Error Information;
    endif
else (No)
endif
stop

@enduml