@startuml CreateAttendance

skinparam ConditionEndStyle hline
skinparam conditionStyle diamond
skinparam Monochrome true
skinparam Shadowing false

|Caller|
start
:Migrate "Approved" requester to Attendance;

|System|
:Validate Data;

if (Valid ?) then (Yes)
    :Insert "Attendance" data to Database;
    
    if (Is Created ?) then (Yes)
        :Adding Success Information;
    else (No)
        :Adding Error Information;
    endif
else (No)
endif
stop

@enduml