@startuml GetBenchmark

skinparam ConditionEndStyle hline
skinparam Monochrome true
skinparam Shadowing false

|Admin|
start
:Open "Dashboard" Page;

|System|
:Get Count of Event from Database;
:Get Count of Class from Database;
:Display the data from card;

stop

@enduml