@startuml GetCalendar

skinparam ConditionEndStyle hline
skinparam conditionStyle diamond
skinparam Monochrome true
skinparam Shadowing false

|Admin|
start
:Open "Dashboard" Page;

|System|
:Get Class from Database;
:Mapping data to Calendar View;
:Display the data to database;

stop

@enduml