@startuml GetClassAvailability

skinparam ConditionEndStyle hline
skinparam Monochrome true
skinparam Shadowing false

|Member|
start
:Open "Class List" Page;

|System|
:Get Available data of "Class" from Database;
:Display the data from card;

stop

@enduml