@startuml GetRequested

skinparam ConditionEndStyle hline
skinparam Monochrome true
skinparam Shadowing false

|Member|
start
:Open "Ticket" Page;

|System|
:Get "Requested Class" of User from Database;
:Display the data to Card;

stop

@enduml