@startuml GetRequester

skinparam ConditionEndStyle hline
skinparam conditionStyle diamond
skinparam Monochrome true
skinparam Shadowing false

|Admin|
start
:Open "Class Detail" Page;

|System|
:Get "Requester" data from Database;
:Display the data to table;

stop

@enduml