@startuml CheckValidityOfTransaction

skinparam ConditionStyle hline
skinparam Monochrome true
skinparam Shadowing false
hide footbox

actor Caller
participant "RoomTransaction: GRPC Transport" as RoomTransactionGRPCTransport
participant "RoomTransaction: Service" as RoomTransactionService
participant "RoomTransaction: Query" as RoomTransactionQuery

Caller->RoomTransactionGRPCTransport: IsValidTransaction(ProtoBuffer)
RoomTransactionGRPCTransport->RoomTransactionService: IsValidTransaction(context, payload)
RoomTransactionService->RoomTransactionQuery: Count(context, []SliceCondition)
RoomTransactionQuery-->RoomTransactionService: total
RoomTransactionService-->RoomTransactionGRPCTransport: total == 0
RoomTransactionGRPCTransport-->Caller: total == 0

@enduml