@startuml CreateRoomTransaction

skinparam ConditionStyle hline
skinparam Monochrome true
skinparam Shadowing false
hide footbox

actor Caller
participant "RoomTransaction: Service" as RoomTransactionService
participant "RoomTransaction: Command" as RoomTransactionCommand
participant "Nats Streaming" as NatsStreaming

Caller->RoomTransactionService: Create(context, payload)
RoomTransactionService->RoomTransactionService: Validate()

alt "Data Not Valid"
    RoomTransactionService-->Caller: UnprocessableEntity
else
    loop "For each shift"
        RoomTransactionService->RoomTransactionService: rt := RoomTransactionModel()
        RoomTransactionService->RoomTransactionCommand: Create(context, rt)
        RoomTransactionCommand-->RoomTransactionService: uuid
    end

    RoomTransactionService->NatsStreaming: publishTransactionCreated(context, []uuid)
    NatsStreaming-->RoomTransactionService: published
    RoomTransactionService-->Caller: created
end

@enduml