@startuml DeleteRoomTransaction

skinparam ConditionStyle hline
skinparam Monochrome true
skinparam Shadowing false
hide footbox

actor Caller
participant "RoomTransaction: Service" as RoomTransactionService
participant "RoomTransaction: Command" as RoomTransactionCommand
participant "RoomTransaction: Query" as RoomTransactionQuery
participant "Nats Streaming" as NatsStreaming

Caller->RoomTransactionService: Delete(context, payload)
RoomTransactionService->RoomTransactionService: Validate()

alt "Data Not Valid"
    RoomTransactionService-->Caller: UnprocessableEntity
else
    RoomTransactionService->RoomTransactionQuery: Find(context, []SliceCondition)
    activate RoomTransactionQuery
    RoomTransactionQuery-->RoomTransactionService: roomTrans
    deactivate RoomTransactionQuery
    
    loop "For each roomTrans"
        RoomTransactionService->RoomTransactionCommand: Delete(context, roomTransaction)
        activate RoomTransactionCommand
        RoomTransactionCommand-->RoomTransactionService: boolean
        deactivate RoomTransactionCommand
    end

    RoomTransactionService->NatsStreaming: publishTransactionDeleted(context, []id)
    NatsStreaming-->RoomTransactionService: published
    RoomTransactionService-->Caller: deleted
end

@enduml