@startuml DeleteRoomTransactionETL

skinparam ConditionStyle hline
skinparam Monochrome true
skinparam Shadowing false
hide footbox

actor Caller
participant "RoomTransactionETL: Service" as RoomTransactionETLService
participant "RoomTransactionETL: Command" as RoomTransactionETLCommand

activate Caller

Caller->RoomTransactionETLService: DeletePersistance()
activate RoomTransactionETLService
RoomTransactionETLService->RoomTransactionETLCommand: DeleteBulk([]id)
activate RoomTransactionETLCommand
RoomTransactionETLCommand-->RoomTransactionETLService: Is Deleted
deactivate RoomTransactionETLCommand
RoomTransactionETLService-->Caller: Is Deleted
deactivate RoomTransactionETLService

deactivate Caller

@enduml