@startuml DeleteRoomTransactionETL

skinparam ConditionStyle hline
skinparam Monochrome true
skinparam Shadowing false
hide footbox

actor Caller
participant "RoomTransactionETL: Service" as RoomTransactionETLService
participant "RoomTransactionETL: Command" as RoomTransactionETLCommand

Caller->RoomTransactionETLService: DeletePersistance(conn, looger, service)
RoomTransactionETLService->RoomTransactionETLCommand: DeleteBulk([]id)
RoomTransactionETLCommand-->RoomTransactionETLService: Is Deleted
RoomTransactionETLService-->Caller: Is Deleted

@enduml