@startuml DeleteUserETL

skinparam ConditionStyle hline
skinparam Monochrome true
skinparam Shadowing false
hide footbox

actor Caller
participant "UserETL: Service" as UserETLService
participant "UserETL: Command" as UserETLCommand

activate Caller

Caller->UserETLService: DeletePersistance()
activate UserETLService
UserETLService->UserETLCommand: Delete(id)
activate UserETLCommand
UserETLCommand-->UserETLService: Is Deleted
deactivate UserETLCommand
UserETLService-->Caller: Is Deleted
deactivate UserETLService

deactivate Caller

@enduml