@startuml SubscribeUserCreated

skinparam ConditionStyle hline
skinparam Monochrome true
skinparam Shadowing false
hide footbox

actor Caller
participant "UserETL: NATS Transport" as UserETLNATSTransport
participant "UserETL: Service" as UserETLService

activate Caller

Caller->UserETLNATSTransport: userCreatedSubscriber
activate UserETLNATSTransport
UserETLNATSTransport->UserETLNATSTransport: parse message
UserETLNATSTransport->UserETLService: Create(User)
activate UserETLService
UserETLService-->UserETLNATSTransport: subscribed
deactivate UserETLService
UserETLNATSTransport-->Caller: subscribed
deactivate UserETLNATSTransport

deactivate Caller

@enduml