@startuml SubscribeRTCreated

skinparam ConditionStyle hline
skinparam Monochrome true
skinparam Shadowing false
hide footbox

actor Caller
participant ":RoomTransactionETLNATS Transport" as RoomTransactionETLNATSTransport
participant ":RoomTransactionETLService" as RoomTransactionETLService

Caller->RoomTransactionETLNATSTransport: replicaRoomTransctionSubscriber(conn, logger, service)
RoomTransactionETLNATSTransport->RoomTransactionETLService: ReplicaPersistance(context, payload)
RoomTransactionETLService-->RoomTransactionETLNATSTransport: subscribed
RoomTransactionETLNATSTransport-->Caller: subscribed

@enduml