@startuml SubscribeRTDeleted

skinparam ConditionStyle hline
skinparam Monochrome true
skinparam Shadowing false
hide footbox

actor Caller
participant "RoomTransactionETL: NATS Transport" as RoomTransactionETLNATSTransport
participant "RoomTransactionETL: Service" as RoomTransactionETLService

Caller->RoomTransactionETLNATSTransport: roomTransactionDeletedSubscriber(conn, logger, service)
RoomTransactionETLNATSTransport->RoomTransactionETLService: DeletePersistance(context, []id)
RoomTransactionETLService-->RoomTransactionETLNATSTransport: subscribed
RoomTransactionETLNATSTransport-->Caller: subscribed

@enduml