@startuml SubscribeRTDeleted

skinparam ConditionStyle hline
skinparam Monochrome true
skinparam Shadowing false
hide footbox

actor Caller
participant "RoomTransactionETL: NATS Transport" as RoomTransactionETLNATSTransport
participant "RoomTransactionETL: Service" as RoomTransactionETLService

activate Caller

Caller->RoomTransactionETLNATSTransport: roomTransactionDeletedSubscriber
activate RoomTransactionETLNATSTransport
RoomTransactionETLNATSTransport->RoomTransactionETLNATSTransport: parse message
RoomTransactionETLNATSTransport->RoomTransactionETLService: DeletePersistance()
activate RoomTransactionETLService
RoomTransactionETLService-->RoomTransactionETLNATSTransport: subscribed
deactivate RoomTransactionETLService
RoomTransactionETLNATSTransport-->Caller: subscribed
deactivate RoomTransactionETLNATSTransport

deactivate Caller

@enduml