@startuml SubscribeUserCreated

skinparam ConditionStyle hline
skinparam Monochrome true
skinparam Shadowing false
hide footbox

actor Caller
participant "UserETL: NATS Transport" as UserETLNATSTransport
participant "UserETL: Service" as UserETLService

Caller->UserETLNATSTransport: userCreatedSubscriber(conn, logger, service)
UserETLNATSTransport->UserETLService: ReplicaPersistance(context, payload)
UserETLService-->UserETLNATSTransport: subscribed
UserETLNATSTransport-->Caller: subscribed

@enduml