@startuml GetShift

skinparam Monochrome true
skinparam Shadowing false
hide footbox

actor Admin
participant "Page: Shift" as ShiftPage
participant "Container: Shift Table" as ShiftTableContainer
participant "Component: Shift Table" as ShiftTable
participant "Router" as Router
participant "Shift: HTTP Transport" as ShiftHTTPTransport
participant "Shift: Endpoint" as ShiftEndpoint
participant "Shift: Service" as ShiftService
participant "Shift: Query" as ShiftQuery

activate Admin

Admin->ShiftPage: Open "Manage Shift" Page
activate ShiftPage
ShiftPage->ShiftTableContainer: Render "Shift Table" Container
activate ShiftTableContainer
ShiftTableContainer->ShiftTable: Render "Shift Table"
activate ShiftTable
ShiftTable-->ShiftTableContainer: rendered
ShiftTableContainer->Router: route("GET", "v2/shifts")
activate Router
Router->ShiftHTTPTransport: FetchPaginatedShifts(ShiftService, []ServerOption)
activate ShiftHTTPTransport
ShiftHTTPTransport->ShiftEndpoint: All(ShiftService, withPaginated)
activate ShiftEndpoint
ShiftEndpoint->ShiftService: All(params)

activate ShiftService
activate ShiftQuery
alt "With Paginate"
    ShiftService->ShiftQuery: All([]SliceConditions, PaginateModel)
else
    ShiftService->ShiftQuery: All([]SliceConditions, nil)
end
ShiftQuery-->ShiftService: shifts
ShiftService-->ShiftEndpoint: shifts

opt "With Paginate"
    ShiftEndpoint->ShiftService: GetPagination(PaginateModel)
    ShiftService->ShiftQuery: Count([]SliceConditions)
    ShiftQuery-->ShiftService: total
    ShiftService-->ShiftEndpoint: total
end
deactivate ShiftQuery
deactivate ShiftService

ShiftEndpoint->ShiftEndpoint: response := Response(shifts, paginateMetadata)
ShiftEndpoint-->ShiftHTTPTransport: response
deactivate ShiftEndpoint
ShiftHTTPTransport-->Router: response
deactivate ShiftHTTPTransport
Router-->ShiftTableContainer: response
deactivate Router
ShiftTableContainer->ShiftTable: Render "Shift Table"
ShiftTable-->ShiftTableContainer: rendered
deactivate ShiftTable
ShiftTableContainer-->ShiftPage: rendered
deactivate ShiftTableContainer
ShiftPage-->Admin: rendered
deactivate ShiftPage

deactivate Admin

@enduml