@startuml SubscribeClassCreated

skinparam ConditionStyle hline
skinparam Monochrome true
skinparam Shadowing false
hide footbox

actor Caller
participant "RoomTransaction: NATS Transport" as RoomTransactionNATSTransport
participant "RoomTransaction: Service" as RoomTransactionService

Caller->RoomTransactionNATSTransport: classCreatedSubscriber
RoomTransactionNATSTransport->RoomTransactionNATSTransport: parse message
RoomTransactionNATSTransport->RoomTransactionService: Create(context, TransactionClass)
RoomTransactionService-->RoomTransactionNATSTransport: subscribed
RoomTransactionNATSTransport-->Caller: subscribed

@enduml