@startuml UpdateAttendance

skinparam ConditionEndStyle hline
skinparam Monochrome true
skinparam Shadowing false

|Caller|
start
:Update Attendance;

|System|
:Validate;

if (Valid ?) then (Yes)
    :Update "Attendance" data from Database;

    if (IsUpdated ?) then (Yes)
        :Adding Success Information;
    else (No)
        :Adding Error Information;
    endif
    
    stop
else (No)
    stop
endif

@enduml