@startuml AnnounceRequest

skinparam ConditionEndStyle hline
skinparam conditionStyle diamond
skinparam Monochrome true
skinparam Shadowing false

|Caller|
start
:Announce Request;

|System|
while("for each accepted requestor") is ("has accepted")
    :Build Template Tag Payload for "Accepted" Status;
endwhile

while("for each low priority requestor") is ("has low priority")
    :Build Template Tag Payload for "Low Priority" Status;
endwhile

while("for each rejected requestor") is ("has accepted")
    :Build Template Tag Payload for "Rejected" Status;
endwhile

|Template Tag CMS|
:Compile Message;

|System|
:Send Email;
stop

@enduml