@startuml Like

skinparam ConditionEndStyle hline
skinparam conditionStyle diamond
skinparam Monochrome true
skinparam Shadowing false

|Member|
start
:Click Empty "Love" Button;

|System|
:Insert "Favourite" data to Database;
if (IsCreated ?) then (Yes)
    :Adding Success Information;
else (No)
    :Adding Error Information;
endif
stop

@enduml