@startuml MAILER_SubscribeCommitRequest

skinparam ConditionEndStyle hline
skinparam conditionStyle diamond
skinparam Monochrome true
skinparam Shadowing false

|Caller|
start
:Subscribe Requests.RequestUpdated;

|System|
:Parsing Event Message;

if (Valid ?) then (Yes)
    :Grouping Requester per Status;
    :Send Email Announcement for each Requester based on Status;

    if (Is Error ?) then (Yes)
        :Adding Error Information;
    endif
endif
stop

@enduml