@startuml Unlike

skinparam ConditionEndStyle hline
skinparam conditionStyle diamond
skinparam Monochrome true
skinparam Shadowing false

|Member|
start
:Click Filled "Love" Button;

|System|
:Delete "Favourite" data from Database;
if (IsCreated ?) then (Yes)
    :Adding Success Information;
else (No)
    :Adding Error Information;
endif
stop

@enduml