@startuml UnreadNotification

skinparam ConditionEndStyle hline
skinparam conditionStyle diamond
skinparam Monochrome true
skinparam Shadowing false

|Member|
start
:Render Header Component;

|System|
:Get "Count of Unread Notification" from Database;

if (More than 0) then (Yes)
    :Display New Notification Indicator;
endif
stop

@enduml